name: foc_companion
description: "FOC Companion App"
publish_to: 'none'
version: 1.1.7+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Communication
  protobuf: ^6.0.0
  usb_serial: ^0.5.0
  libserialport: ^0.3.0 # For Desktop
  web_socket_channel: ^2.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  file_picker: ^8.1.7
  path_provider: ^2.1.2
  
  # Logging
  logger: ^2.0.0

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  share_plus: ^10.1.4
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
